Pan other way once end is reached (#2)
* - attempt to fix issue: https://github.com/MaelstromJS/PanningView/issues/1
  > make update() call private and have it only called from stopPanning() if panning is already in progress

I'll squash and merge this. Looks fine. Will release a new version on maven in the near future. (Caught up in college coursework).
  > comment out update() call from layout change.. I want to test this but I'm wondering if we really need to reset direction when this happens

* - testing showed that update() was being called a LOT.. without it panning seems a lot smoother to me. The direction WAS changed now but still not animating the other way. I'm adding a few log statements and will keep testing

* - remove support library (seeing compile error with @NonNull annotation and not sure why we need this anyway)
- update gradle libraries

* - update (note to self.. need to figure out how to test locally w/out relying on jitpack.io...)

* - fixes https://github.com/MaelstromJS/PanningView/issues/1

* - fixes https://github.com/MaelstromJS/PanningView/issues/1

* - fix Android Studio Preview view error by checking for isEditMode()
  > java.lang.NoClassDefFoundError: com/maelstrom/panning/R$styleable   at com.maelstrom.panning.PanningImageView.readStyleParameters(PanningImageView.java:34)
- remove commented out logic

* - fixes another design view Exception
> java.lang.IllegalArgumentException: Please define the src attribute of the ImageView
	at com.maelstrom.panning.PanningImageViewAttacher.<init>(PanningImageViewAttacher.java:46)
	at com.maelstrom.panning.PanningImageView.<init>(PanningImageView.java:31)
	at com.maelstrom.panning.PanningImageView.<init>(PanningImageView.java:22)

* - forgot to initialize mAttacher.. keep the isInEditMode() check simple